export const routes = {
  doctor: {
    dashboard: '/doctor',
    create: '/doctor/create',
    edit: (id: string) => `/doctor/edit/${id}`,
    doctorDetail: (id: string) => `/doctor/${id}`,
    setting: '/doctor/setting',
  },
  user: {
    dashboard: '/user',
    create: '/user/create',
    edit: (id: string) => `/user/edit/${id}`,
    userDetail: (id: string) => `/user/${id}`,
  },
  product: {
    dashboard: '/product',
    create: '/product/create',
    edit: (id: string) => `/product/edit/${id}`,
    productDetail: (id: string) => `/product/view/${id}`,
  },
  patient: {
    dashboard: '/patient',
    create: '/patient/create',
    edit: (id: string) => `/patient/edit/${id}`,
    patientDetail: (id: string) => `/patient/${id}`,
  },
  management: {
    dashboard: '/management',
  },
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
  },
  setting: {
    setup: '/setting/setup',
    communication: '/setting/communication',
    payment: '/setting/payment',
    notificationReminder: '/setting/notification-reminder',
    emailTemplate: '/setting/email-template',
    smsTemplate: '/setting/sms-template',
  },

  // Patient
  myDashboard: '/my-dashboard',
  myAppointment: {
    dashboard: '/my-appointment',
    upcoming: '/my-appointment/upcoming',
    previous: '/my-appointment/previous',
  },
  myFamily: {
    dashboard: '/my-family',
    announcement: '/my-family/announcement',
    familyList: '/my-family/family-list',
  },
  paymentMethods: '/payment-methods',
  myAccountDetails: '/my-account-details',
  bookAppointment: '/bookings',
  consentForm: '/form/consent-form',
  consentFormConfirmation: '/form/consent-form/confirmation',

  eCommerce: {
    dashboard: '/ecommerce',
    products: '/ecommerce/products',
    createProduct: '/ecommerce/products/create',
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: '/ecommerce/categories',
    createCategory: '/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  appointment: {
    dashboard: '/appointment',
    appointmentList: '/appointment/list',
  },
  crm: {
    dashboard: '/crm',
  },
  executive: {
    dashboard: '/executive',
  },
  project: {
    dashboard: '/project',
  },
  socialMedia: {
    dashboard: '/social-media',
  },
  jobBoard: {
    dashboard: '/job-board',
    jobFeed: '/job-board/feed',
  },
  eventCalendar: '/event-calendar',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  profile: '/profile',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp: '/auth/sign-up',
    signIn: '/auth/sign-in',
    forgotPassword: '/auth/forgot-password',
    otp: '/auth/otp',
  },
  signIn: '/auth/sign-in',
};
