export const routes = {
  doctor: {
    dashboard: '/doctor',
    create: '/doctor/create',
    edit: (id: string) => `/doctor/edit/${id}`,
    doctorDetail: (id: string) => `/doctor/${id}`,
    setting: '/doctor/setting',
  },
  user: {
    dashboard: '/user',
    create: '/user/create',
    edit: (id: string) => `/user/edit/${id}`,
    userDetail: (id: string) => `/user/detail/${id}`,
  },
  patient: {
    list: '/patient',
    setting: '/patient/setting',
    create: '/patient/create',
    edit: (id: string) => `/patient/edit/${id}`,
    patientDetail: (id: string) => `/patient/${id}`,
  },
  management: {
    dashboard: '/management',
    product: {
      list: '/management/product',
      create: '/management/product/create',
      edit: (id: string) => `/management/product/edit/${id}`,
      productDetail: (id: string) => `/management/product/view/${id}`,
    },
  },
  marketing: {
    coupon: '/marketing/coupon',
    emailMarketing: '/marketing/email-broadcast',
    smsMarketing: '/marketing/sms-broadcast',
    subscribePromotion: '/marketing/subscribe-promotion',
  },
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
  },
  sales: {
    creditNotes: '/credit-notes',
  },
  requestCallBack: '/requestcallback',
  communications: {
    sms: '/sms-communication',
    email: '/email-communication',
    socialMedia: 'social-media-communication',
  },
  report: '/report',
  reportAnalytics: {
    businessInsight: '/business-insight',
    revenueGrowth: '/revenue-growth',
    churnRetention: '/churn-retention',
    billingTransaction: '/billing-transaction',

    clinicPerformance: '/clinic-performance',
    clinicOverview: '/clinic-overview',
    doctorStaffProductivity: '/doctor-staff-productivity',
    appointmentCapacity: '/appointment-capacity',
    serviceInsight: '/service-insight',

    patientEngagement: '/patient-engagement',
    patientGrowth: '/patient-growth',
    engagementTrends: '/engagement-trends',
    satisfactionScores: '/ satisfaction-scores',
    communicationAnalytics: '/communication-analytics',
    referralSources: '/referral-sources',

    financialReports: '/financial-reports',
    revenueBreakdown: '/revenue-breakdown',
    accountsReceivable: '/accounts-receivable',
    paymentAnalysis: '/payment-analysis',
    refundAdjustments: '/refund-adjustments',
    financialForecasting: '/financial-forecasting',

    marketingInsights: '/marketing-nsights',
    trafficOverview: '/traffic-overview',
    acquisitionChannels: '/acquisition-channels',
    campaignPerformance: '/campaign-performance',
    seoKeywordInsight: '/seoKeyword-insight',
    conversionFunnel: '/conversion-funnel',
    adSpendROI: '/ad-spend-roi',

    customReports: '/custom-reports',
  },
  setting: {
    setup: '/setting/setup',
    communication: '/setting/communication',
    payment: '/setting/payment',
    notificationReminder: '/setting/email-notification-reminder',
    smsNotificationReminder: '/setting/sms-notification-reminder',
    emailTemplate: '/setting/email-template',
    smsTemplate: '/setting/sms-template',
    roles: '/setting/roles',
    dateTimeFormat: '/setting/date-time-format',
    taxSettings: '/setting/tax',
    invoiceSettings: '/setting/invoice-settings',
    branch: '/setting/branch',
    currency: '/setting/currency',
  },
  pharmachy: '/pharmacy',
  bookAppointment: '/bookings',
  consentForm: '/form/consent-form',
  consentFormConfirmation: '/form/consent-form/confirmation',
  appointment: {
    dashboard: '/dashboard',
    appointmentList: '/appointment/list',
  },
  calendar: '/calendar',
  globalCalendar: '/global-calendar',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  profile: '/profile',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp: '/auth/sign-up',
    signIn: '/auth/sign-in',
    forgotPassword: '/auth/forgot-password',
    otp: '/auth/otp',
  },
  signIn: '/auth/sign-in',
  connection: {
    api: '/connection/api',
    connect: '/connection/connect',
  },
};
